### ISSUE TITLE
Rewrite oxf-wms-adapter

### ISSUE THREAD

**Issue by matthesrieke** [52North/OX-Framework#2]
The WMS adapter is marked as deprecated. It should be rewritten and reactivated if there is a need for a WMS adapter, in particular with support for WMS Spec Version 1.3.0.

> Good starting point for rewriting would be to integrate geotools
> 
> http://docs.geotools.org/latest/userguide/extension/wms/wms.html
> 
> geotools is very active and has great community which indicates a reliable and sustainable support (not only) for connecting WMS (including 1.3.0)

**Comment by EHJ-52n** [comment]
Closed because project is archived.
