### ISSUE TITLE
No MIME-TYPE override possible

### ISSUE THREAD

**Issue by ridoo** [52North/OX-Framework#30]
Currently the SosAdapter implementation sets the `text/xml` mime type internally and does not let to override it. This leads servers `application/soap+xml` to be unsupported.

**Proposed workaround:**
add a `mimetype` parametershell with the mimetype we want to send the request with. 

**On the long run:** 
the OX-F should not encapsulate too much so that these kind of things can be overridden by applications.

**Comment by EHJ-52n** [comment]
Closed because project is archived.
