### ISSUE TITLE
SOSWrapper.doDeleteSensor does not set Binding

### ISSUE THREAD

**Issue by MalikAtalla-AI** [52North/OX-Framework#44]
The method doDeleteSensor in org.n52.oxf.sos.adapter.wrapper.SOSWrapper, unlike all other public methods in this class, does not set the binding. The logger states that POX will be used as default, but the actual behaviour is a incoherent. It seems that /service/exi is used as the service uri, but the request body contains POX.

**Comment by EHJ-52n** [comment]
Dear @MalikAtalla-AI,
thank you for posting this issue. Could you give some more details on the environment, you used to produce the error. In addition, it would help a lot, if you post the log output with level DEBUG.
Kind regards,
Eike

**Comment by MalikAtalla-AI** [comment]
About the machine: Virtual machine with
 * ubuntu 14.04 LTS
 * 16GB Ram
 * Intel® Xeon(R) CPU E5-1607 v2 @ 3.00GHz × 2
 * Gallium 0.4 on SVGA3D; build: RELEASE; 
 * 64-bit OS
 * 38 GB disk

**Comment by EHJ-52n** [comment]
Closed because project is archived.
